name: continuous-integration

on:
#  push:
#    branches: [main]
#  pull_request:
#    branches: [main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        bun-version: ['1.x']

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - run: bun i
      - run: bun test
